/**
-- Resoource Links:
-- https://www.bnl.gov/phobos/Detectors/Computing/Orant/doc/sqlplus.804/a53717/ch4.htm
-- https://www2.uwe.ac.uk/services/its/Documents/Computer%20Science%20Support%20pdfs/Computer%20Science%209%20-%20SQLPlus%20-%20Setting%20Line%20And%20Page%20Sizes.pdf
**/

-- CLI Properties
SET linesize 300;
SET pagesize 300;

/**
-- COLUMN PROPERTIES
**/

--PilotInfo
COLUMN PILOTID FORMAT A10;
COLUMN PILOTNAME FORMAT A20;
COLUMN CATEGORY FORMAT A15;
COLUMN NATIONALITY FORMAT A15;
COLUMN FLYINGHOUR FORMAT A10;

--Airlines
COLUMN AIRLINEID FORMAT A8;
COLUMN AIRLINENAME FORMAT A20;
COLUMN VEHICLEMODEL FORMAT A15;
COLUMN AIRLINEORIGIN FORMAT A15;
COLUMN AIRLINERATING FORMAT A10;

-- Aggregation
COLUMN AGGREGATEID FORMAT A11;

--Bookings
COLUMN BOOKINGID FORMAT A10;
COLUMN CUSTOMERNAME FORMAT A20;
COLUMN BOOKINGDEPERTURE FORMAT A15;
COLUMN BOOKINGDEST FORMAT A15;
COLUMN AIRLINENAME FORMAT A20;
COLUMN CATEGORY FORMAT A15;

--Ratings
COLUMN RATINGID FORMAT A10;
COLUMN RATING FORMAT A15;
COLUMN AIRLINENAME FORMAT A20;
COLUMN CATEGORY FORMAT A15;

--Passengers
COLUMN PASSENGERID FORMAT A10;
COLUMN PASSENGERNAME FORMAT A20;
COLUMN BOOKINGID FORMAT A15;
COLUMN AIRLINENAME FORMAT A20;
COLUMN CATEGORY FORMAT A15;
COLUMN PASSENGERPHONE FORMAT A15;
COLUMN PASSENGEREMAIL FORMAT A15;


--Ticketing 
COLUMN TICKETID FORMAT A10;
COLUMN BOOKINGID FORMAT A15;
COLUMN FLYINGDATE FORMAT A20;



commit;